-- CreateTable
CREATE TABLE "RppgV8Session" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "rmssd" DOUBLE PRECISION NOT NULL,
    "hf" DOUBLE PRECISION NOT NULL,
    "lfHfRatio" DOUBLE PRECISION NOT NULL,
    "heartRate" DOUBLE PRECISION NOT NULL,
    "hrv" DOUBLE PRECISION NOT NULL,
    "estimatedSpO2" DOUBLE PRECISION NOT NULL,
    "skinTemperature" DOUBLE PRECISION NOT NULL,
    "hrTrend" DOUBLE PRECISION,
    "meanEda" DOUBLE PRECISION NOT NULL,
    "meanTemp" DOUBLE PRECISION NOT NULL,
    "asi" DOUBLE PRECISION,
    "rmssdTrend" DOUBLE PRECISION,
    "ac" DOUBLE PRECISION,
    "dc" DOUBLE PRECISION,
    "acDcRatio" DOUBLE PRECISION,
    "pulseAmplitude" DOUBLE PRECISION,
    "signalQuality" DOUBLE PRECISION,
    "respiratoryRate" DOUBLE PRECISION,
    "sessionType" TEXT NOT NULL DEFAULT 'checkin',
    "sessionQuality" TEXT,
    "capturedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "RppgV8Session_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RppgV8PredictionResult" (
    "id" TEXT NOT NULL,
    "userId" TEXT NOT NULL,
    "predictedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "nSessionsUsed" INTEGER NOT NULL,
    "sleepQualityScore" DOUBLE PRECISION,
    "focusMemoryScore" DOUBLE PRECISION,
    "mentalWellnessScore" DOUBLE PRECISION,
    "moodScoreScore" DOUBLE PRECISION,
    "metabolicSyndromeScore" DOUBLE PRECISION,
    "t2dScore" DOUBLE PRECISION,
    "cardiovascularScore" DOUBLE PRECISION,
    "heartFailureScore" DOUBLE PRECISION,
    "chronicStressScore" DOUBLE PRECISION,
    "infertilityScore" DOUBLE PRECISION,
    "riskSleepQualityScore" DOUBLE PRECISION,
    "riskSleepQualityProb" DOUBLE PRECISION,
    "riskSleepQualityFlag" INTEGER,
    "riskSleepQualitySeverity" TEXT,
    "riskFocusMemoryScore" DOUBLE PRECISION,
    "riskFocusMemoryProb" DOUBLE PRECISION,
    "riskFocusMemoryFlag" INTEGER,
    "riskFocusMemorySeverity" TEXT,
    "riskMentalWellnessScore" DOUBLE PRECISION,
    "riskMentalWellnessProb" DOUBLE PRECISION,
    "riskMentalWellnessFlag" INTEGER,
    "riskMentalWellnessSeverity" TEXT,
    "riskMoodCheckScore" DOUBLE PRECISION,
    "riskMoodCheckProb" DOUBLE PRECISION,
    "riskMoodCheckFlag" INTEGER,
    "riskMoodCheckSeverity" TEXT,
    "riskMetabolicScore" DOUBLE PRECISION,
    "riskMetabolicProb" DOUBLE PRECISION,
    "riskMetabolicFlag" INTEGER,
    "riskMetabolicSeverity" TEXT,
    "riskT2dScore" DOUBLE PRECISION,
    "riskT2dProb" DOUBLE PRECISION,
    "riskT2dFlag" INTEGER,
    "riskT2dSeverity" TEXT,
    "riskCvdScore" DOUBLE PRECISION,
    "riskCvdProb" DOUBLE PRECISION,
    "riskCvdFlag" INTEGER,
    "riskCvdSeverity" TEXT,
    "riskHeartFailureScore" DOUBLE PRECISION,
    "riskHeartFailureProb" DOUBLE PRECISION,
    "riskHeartFailureFlag" INTEGER,
    "riskHeartFailureSeverity" TEXT,
    "riskChronicStressScore" DOUBLE PRECISION,
    "riskChronicStressProb" DOUBLE PRECISION,
    "riskChronicStressFlag" INTEGER,
    "riskChronicStressSeverity" TEXT,
    "riskInfertilityScore" DOUBLE PRECISION,
    "riskInfertilityProb" DOUBLE PRECISION,
    "riskInfertilityFlag" INTEGER,
    "riskInfertilitySeverity" TEXT,
    "dlSleepQualityScore" DOUBLE PRECISION,
    "dlFocusMemoryScore" DOUBLE PRECISION,
    "dlMentalWellnessScore" DOUBLE PRECISION,
    "dlMoodScoreScore" DOUBLE PRECISION,
    "moodCheckLabel" TEXT,
    "moodCheckConfidence" DOUBLE PRECISION,
    "moodCheckProbabilities" JSONB,

    CONSTRAINT "RppgV8PredictionResult_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "RppgV8Session" ADD CONSTRAINT "RppgV8Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RppgV8PredictionResult" ADD CONSTRAINT "RppgV8PredictionResult_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
